<a href="https://colab.research.google.com/github/HARIPRASATH-R-44/Machine-learning-and-data-science-notes-and-practice/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

### NumPy is used to do scientific computing and data manipulation and calculations.

---


Importing Numpy library

In [1]:
import numpy as np

Numpy array vs List

In [23]:
# MEMORY CONSUMPTION TEST
import sys
list1= range(1000)
print(sys.getsizeof(5)*len(list1))

28000


In [24]:
array=np.arange(1000)
print(array.size*array.itemsize)

8000


In memory consumption test Numpy array won !!

In [26]:
#Speed test
import time
size=100000000
list1=range(size)
list2 =range(size)

start= time.time()
sum=[(x+y) for x,y in zip(list1,list2) ]
print("time taken : ",(time.time()-start))

time taken :  18.299985647201538


In [27]:
array1 =np.arange(size)
array2=np.arange(size)

start =time.time()
sum2=array1 +array2
print("time taken : ",(time.time()-start))

time taken :  0.6254541873931885


And again NumPy array wins !!


---



1 dimensional array


In [6]:
array1 =np.array([1,2,3,4])
array1

array([1, 2, 3, 4])

Creating a numpy array using array range function

In [13]:
arr= np.arange(1,5)
arr

array([1, 2, 3, 4])

In [31]:
print("dimension: ",arr.ndim) # to get dimension of the array
print("size: ",arr.size) # to get the size of the array
print("size of individual element: ",arr.itemsize) # to get size of a single element in the array
print("datatype: ",array.dtype )# to get the datatype of the element present in the array

dimension:  1
size:  4
size of individual element:  8
datatype:  int64


2 dimensional array

In [12]:
array_2d =np.array([[1,2],[3,4],[5,6]])
array_2d

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
array_2d.shape

(3, 2)

"**3**" refers to the no of rows and "**2**" refers to the no of column

In [22]:
array_2d.reshape((2,3))
print(array_2d)
print(array_2d.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [10]:
for cell in array1:
  print(cell)

1
2
3
4
